import { BaseAgent } from "./base.js";
import type { ArchitectOutput } from "./architect.js";
import {
  ANTAGONIST_INTELLIGENCE_CHECKLIST,
  GOLDEN_OPENING_REVIEW_CHECKLIST,
  SIX_STEP_PLOT_METHOD,
  WORLD_ENGINE_METHOD,
} from "../story-methods/index.js";

export interface FoundationReviewResult {
  readonly passed: boolean;
  readonly totalScore: number;
  readonly dimensions: ReadonlyArray<{
    readonly name: string;
    readonly score: number;
    readonly feedback: string;
  }>;
  readonly overallFeedback: string;
}

const PASS_THRESHOLD = 80;
const DIMENSION_FLOOR = 60;
const STORY_CRITICAL_FLOOR = 75;

type StorySkeletonKey =
  | "genreArchitecture"
  | "worldEngine"
  | "antagonistMap"
  | "motivationMatrix"
  | "first10ChapterPlan";

const STORY_SKELETON_FIELDS: ReadonlyArray<{
  readonly key: StorySkeletonKey;
  readonly dimensionKeyword: string;
  readonly zhName: string;
  readonly enName: string;
}> = [
  { key: "genreArchitecture", dimensionKeyword: "genre_architecture_effectiveness", zhName: "题材架构", enName: "Genre Architecture" },
  { key: "worldEngine", dimensionKeyword: "world_engine_effectiveness", zhName: "世界发动机", enName: "World Engine" },
  { key: "antagonistMap", dimensionKeyword: "antagonist_effectiveness", zhName: "反派结构", enName: "Antagonist Structure" },
  { key: "motivationMatrix", dimensionKeyword: "motivation_effectiveness", zhName: "人物动机矩阵", enName: "Motivation Matrix" },
  { key: "first10ChapterPlan", dimensionKeyword: "first_10_chapter_pull", zhName: "前10章规划", enName: "First 10 Chapter Plan" },
];

export function hasFallbackContent(content: string | undefined): boolean {
  if (!content) return false;
  return content.includes("本文件由 inkos 2.0 create 阶段 fallback 生成")
    || content.includes("Generated by inkos 2.0 create-stage fallback");
}

export function countFallbackSections(foundation: ArchitectOutput): number {
  return STORY_SKELETON_FIELDS.filter((field) => hasFallbackContent(foundation[field.key])).length;
}

function countMissingStorySections(foundation: ArchitectOutput): number {
  return STORY_SKELETON_FIELDS.filter((field) => !foundation[field.key]?.trim()).length;
}

export class FoundationReviewerAgent extends BaseAgent {
  get name(): string {
    return "foundation-reviewer";
  }

  async review(params: {
    readonly foundation: ArchitectOutput;
    readonly mode: "original" | "fanfic" | "series";
    readonly sourceCanon?: string;
    readonly styleGuide?: string;
    readonly language: "zh" | "en";
  }): Promise<FoundationReviewResult> {
    const canonBlock = params.sourceCanon
      ? `\n## 原作正典参照\n${params.sourceCanon.slice(0, 8000)}\n`
      : "";
    const styleBlock = params.styleGuide
      ? `\n## 原作风格参照\n${params.styleGuide.slice(0, 2000)}\n`
      : "";

    const dimensions = params.mode === "original"
      ? this.originalDimensions(params.language)
      : this.derivativeDimensions(params.language, params.mode);

    const systemPrompt = params.language === "en"
      ? this.buildEnglishReviewPrompt(dimensions, canonBlock, styleBlock)
      : this.buildChineseReviewPrompt(dimensions, canonBlock, styleBlock);

    const userPrompt = this.buildFoundationExcerpt(params.foundation, params.language);

    const response = await this.chat([
      { role: "system", content: systemPrompt },
      { role: "user", content: userPrompt },
    ], { temperature: 0.3 });

    return this.parseReviewResult(
      response.content,
      dimensions,
      params.foundation,
      params.language,
      params.mode === "original",
    );
  }

  private originalDimensions(language: "zh" | "en"): ReadonlyArray<string> {
    return language === "en"
      ? [
          "Core Conflict (Is there a clear, compelling central conflict that can sustain 40 chapters?)",
          "Opening Momentum (Can the first 5 chapters create a page-turning hook?)",
          "World Coherence (Is the worldbuilding internally consistent and specific?)",
          "Character Differentiation (Are the main characters distinct in voice and motivation?)",
          "Pacing Feasibility (Does the volume outline have enough variety — not the same beat for 10 chapters?)",
          "genre_architecture_effectiveness / Genre Architecture Effectiveness (Is the genre play, reader promise, core emotion, opening hook, and platform selling point clear?)",
          "world_engine_effectiveness / World Engine Effectiveness (Is there a scarce resource, monopoly, power cycle, chain reaction, civilization consensus, protagonist anomaly, and reusable conflict sources?)",
          "antagonist_effectiveness / Core Antagonist Effectiveness (Is there a durable antagonist representing an order, with A/B/C plans, stage antagonist linkage, and no dumb-villain shortcuts?)",
          "motivation_effectiveness / Motivation Effectiveness (Are protagonist, antagonist, and supporting character motives clear enough to constrain future writing?)",
          "first_10_chapter_pull / First 10 Chapter Pull (Do the golden first three chapters and first 10 chapter table create goals, obstacles, solutions, reversals, and ending hooks?)",
          "continuation_usability / Continuation Usability (Can write-next later reuse the new skeletons to reduce drift through conflict sources, antagonist pressure, behavior constraints, and early route?)",
        ]
      : [
          "核心冲突（是否有清晰且有足够张力的核心冲突支撑40章？）",
          "开篇节奏（前5章能否形成翻页驱动力？）",
          "世界一致性（世界观是否内洽且具体？）",
          "角色区分度（主要角色的声音和动机是否各不相同？）",
          "节奏可行性（卷纲是否有足够变化——不会连续10章同一种节拍？）",
          "genre_architecture_effectiveness / 题材架构有效性（是否明确题材玩法、读者承诺、核心爽点、核心情绪、开头钩子和番茄发布卖点？）",
          "world_engine_effectiveness / 世界发动机有效性（是否有稀缺资源、垄断者、权力循环、链式反应、文明共识、主角异常性和可复用冲突来源？）",
          "antagonist_effectiveness / 核心反派有效性（是否有代表秩序/利益的核心反派、A/B/C计划链、阶段反派挂钩和反派不降智规则？）",
          "motivation_effectiveness / 人物动机有效性（主角、核心反派、配角动机是否清晰，并能约束续写行为？）",
          "first_10_chapter_pull / 前10章追读有效性（黄金三章和前10章是否具备目标、阻碍、解决、爽点/反转、结尾钩子和第10章阶段变化？）",
          "continuation_usability / 续写可用性（新增骨架是否能被后续 write next 复用，减少世界、反派、人物和前期路线漂移？）",
        ];
  }

  private derivativeDimensions(language: "zh" | "en", mode: "fanfic" | "series"): ReadonlyArray<string> {
    const modeLabel = mode === "fanfic"
      ? (language === "en" ? "Fan Fiction" : "同人")
      : (language === "en" ? "Series" : "系列");

    return language === "en"
      ? [
          `Source DNA Preservation (Does the ${modeLabel} respect the original's world rules, character personalities, and established facts?)`,
          `New Narrative Space (Is there a clear divergence point or new territory that gives the story room to be ORIGINAL, not a retelling?)`,
          "Core Conflict (Is the new story's central conflict compelling and distinct from the original?)",
          "Opening Momentum (Can the first 5 chapters create a page-turning hook without requiring 3 chapters of setup?)",
          `Pacing Feasibility (Does the outline avoid the trap of re-walking the original's plot beats?)`,
        ]
      : [
          `原作DNA保留（${modeLabel}是否尊重原作的世界规则、角色性格、已确立事实？）`,
          `新叙事空间（是否有明确的分岔点或新领域，让故事有原创空间，而非复述原作？）`,
          "核心冲突（新故事的核心冲突是否有足够张力且区别于原作？）",
          "开篇节奏（前5章能否形成翻页驱动力，不需要3章铺垫？）",
          `节奏可行性（卷纲是否避免了重走原作剧情节拍的陷阱？）`,
        ];
  }

  private buildChineseReviewPrompt(
    dimensions: ReadonlyArray<string>,
    canonBlock: string,
    styleBlock: string,
  ): string {
    return `你是一位资深小说编辑，正在审核一本新书的基础设定（世界观 + 大纲 + 规则）。

你需要从以下维度逐项打分（0-100），并给出具体意见：

${dimensions.map((dim, i) => `${i + 1}. ${dim}`).join("\n")}

## inkos 2.0 故事骨架审核重点
- 题材架构：主分类、子题材、目标读者、平台预期、读者承诺、核心爽点、核心情绪、开头钩子、番茄发布卖点必须具体。
- 世界发动机：${WORLD_ENGINE_METHOD.reviewChecklist?.join("；") ?? "必须能自动产出冲突。"}
- 反派结构：${ANTAGONIST_INTELLIGENCE_CHECKLIST.join("；")}
- 人物动机：主角表层目标/深层欲望/恐惧/底线/不可牺牲项要清楚；反派动机要自洽；配角不能只是工具人。
- 前10章追读：${GOLDEN_OPENING_REVIEW_CHECKLIST.join("；")}；同时检查每章是否有目标、阻碍、解决方法、爽点/反转、结尾钩子。
- 六步闭环：${SIX_STEP_PLOT_METHOD.reviewChecklist.join("；")}
- 续写可用性：新增5个骨架必须能给后续 write next 提供冲突来源、反派压力、人物行为约束和前期推进路线。
- 如果新增 section 缺失或包含“本文件由 inkos 2.0 create 阶段 fallback 生成”，必须扣分并明确指出需要重做。

## 评分标准
- 80+ 通过，可以开始写作
- 60-79 有明显问题，需要修改
- <60 方向性错误，需要重新设计
- world_engine_effectiveness、antagonist_effectiveness、first_10_chapter_pull 任一低于75，都视为需要重做。
- 5个新增 section 有3个以上 fallback 或缺失，总评必须低于80；全部 fallback 或缺失，总评必须低于70。

## 输出格式（严格遵守）
=== DIMENSION: 1 ===
分数：{0-100}
意见：{具体反馈}

=== DIMENSION: 2 ===
分数：{0-100}
意见：{具体反馈}

...（每个维度一个 block）

=== OVERALL ===
总分：{加权平均}
通过：{是/否}
总评：{1-2段总结，指出最大的问题和最值得保留的优点}
${canonBlock}${styleBlock}

审核时要严格。不要因为"还行"就给高分。80分意味着"可以直接开写，不需要改"。`;
  }

  private buildEnglishReviewPrompt(
    dimensions: ReadonlyArray<string>,
    canonBlock: string,
    styleBlock: string,
  ): string {
    return `You are a senior fiction editor reviewing a new book's foundation (worldbuilding + outline + rules).

Score each dimension (0-100) with specific feedback:

${dimensions.map((dim, i) => `${i + 1}. ${dim}`).join("\n")}

## inkos 2.0 Story Skeleton Review Focus
- Genre architecture: primary category, subgenre, target readers, platform expectation, reader promise, core gratification, core emotion, opening hook, and platform selling points must be specific.
- World engine: ${WORLD_ENGINE_METHOD.reviewChecklist?.join("; ") ?? "must automatically generate conflict."}
- Antagonist structure: ${ANTAGONIST_INTELLIGENCE_CHECKLIST.join("; ")}
- Motivation matrix: protagonist surface goal / deep desire / fear / bottom line / non-sacrifice items must be clear; antagonist motivation must be self-consistent; supporting characters cannot be mere tools.
- First 10 chapter pull: ${GOLDEN_OPENING_REVIEW_CHECKLIST.join("; ")}; also check whether each chapter has a goal, obstacle, solution, gratification/reversal, and ending hook.
- Six-step loop: ${SIX_STEP_PLOT_METHOD.reviewChecklist.join("; ")}
- Continuation usability: the five new skeletons must provide conflict sources, antagonist pressure, character behavior constraints, and an early progression route for later write-next use.
- If a new section is missing or contains "Generated by inkos 2.0 create-stage fallback", deduct points and explicitly request regeneration.

## Scoring
- 80+ Pass — ready to write
- 60-79 Needs revision
- <60 Fundamental direction problem
- world_engine_effectiveness, antagonist_effectiveness, or first_10_chapter_pull below 75 means regeneration is required.
- If 3+ of the five new sections are fallback or missing, total must be below 80; if all are fallback or missing, total must be below 70.

## Output format (strict)
=== DIMENSION: 1 ===
Score: {0-100}
Feedback: {specific feedback}

=== DIMENSION: 2 ===
Score: {0-100}
Feedback: {specific feedback}

...

=== OVERALL ===
Total: {weighted average}
Passed: {yes/no}
Summary: {1-2 paragraphs — biggest problem and best quality}
${canonBlock}${styleBlock}

Be strict. 80 means "ready to write without changes."`;
  }

  private buildFoundationExcerpt(foundation: ArchitectOutput, language: "zh" | "en"): string {
    return language === "en"
      ? `## Story Bible\n${foundation.storyBible.slice(0, 3000)}\n\n## Volume Outline\n${foundation.volumeOutline.slice(0, 3000)}\n\n## Book Rules\n${foundation.bookRules.slice(0, 1500)}\n\n## Initial State\n${foundation.currentState.slice(0, 1000)}\n\n## Initial Hooks\n${foundation.pendingHooks.slice(0, 1000)}\n\n## Genre Architecture\n${this.storySectionExcerpt(foundation.genreArchitecture, "genre_architecture", language)}\n\n## World Engine\n${this.storySectionExcerpt(foundation.worldEngine, "world_engine", language)}\n\n## Antagonist Structure\n${this.storySectionExcerpt(foundation.antagonistMap, "antagonist_map", language)}\n\n## Motivation Matrix\n${this.storySectionExcerpt(foundation.motivationMatrix, "motivation_matrix", language)}\n\n## First 10 Chapter Plan\n${this.storySectionExcerpt(foundation.first10ChapterPlan, "first_10_chapter_plan", language)}`
      : `## 世界设定\n${foundation.storyBible.slice(0, 3000)}\n\n## 卷纲\n${foundation.volumeOutline.slice(0, 3000)}\n\n## 规则\n${foundation.bookRules.slice(0, 1500)}\n\n## 初始状态\n${foundation.currentState.slice(0, 1000)}\n\n## 初始伏笔\n${foundation.pendingHooks.slice(0, 1000)}\n\n## 题材架构\n${this.storySectionExcerpt(foundation.genreArchitecture, "genre_architecture", language)}\n\n## 世界发动机\n${this.storySectionExcerpt(foundation.worldEngine, "world_engine", language)}\n\n## 反派结构\n${this.storySectionExcerpt(foundation.antagonistMap, "antagonist_map", language)}\n\n## 人物动机矩阵\n${this.storySectionExcerpt(foundation.motivationMatrix, "motivation_matrix", language)}\n\n## 前10章规划\n${this.storySectionExcerpt(foundation.first10ChapterPlan, "first_10_chapter_plan", language)}`;
  }

  private storySectionExcerpt(
    content: string | undefined,
    sectionName: string,
    language: "zh" | "en",
  ): string {
    const trimmed = content?.trim();
    if (!trimmed) {
      return language === "en"
        ? `[MISSING SECTION: ${sectionName}. This is a quality problem.]`
        : `[缺失 SECTION: ${sectionName}。这是质量问题。]`;
    }
    return trimmed.slice(0, 2500);
  }

  private parseReviewResult(
    content: string,
    dimensions: ReadonlyArray<string>,
    foundation: ArchitectOutput,
    language: "zh" | "en",
    applyStorySkeletonGate: boolean,
  ): FoundationReviewResult {
    const parsedDimensions: Array<{ readonly name: string; readonly score: number; readonly feedback: string }> = [];

    for (let i = 0; i < dimensions.length; i++) {
      const regex = new RegExp(
        `=== DIMENSION: ${i + 1} ===\\s*[\\s\\S]*?(?:分数|Score)[：:]\\s*(\\d+)[\\s\\S]*?(?:意见|Feedback)[：:]\\s*([\\s\\S]*?)(?==== |$)`,
      );
      const match = content.match(regex);
      parsedDimensions.push({
        name: dimensions[i]!,
        score: match ? parseInt(match[1]!, 10) : 50,
        feedback: match ? match[2]!.trim() : "(parse failed)",
      });
    }

    const adjustedDimensions = applyStorySkeletonGate
      ? this.applyStorySkeletonPenalties(parsedDimensions, foundation, language)
      : parsedDimensions;

    const rawTotalScore = adjustedDimensions.length > 0
      ? Math.round(adjustedDimensions.reduce((sum, d) => sum + d.score, 0) / adjustedDimensions.length)
      : 0;
    const cappedTotalScore = applyStorySkeletonGate
      ? this.capTotalForMissingStorySkeleton(rawTotalScore, foundation)
      : rawTotalScore;
    const totalScore = adjustedDimensions.length > 0
      ? cappedTotalScore
      : 0;
    const anyBelowFloor = adjustedDimensions.some((d) => d.score < DIMENSION_FLOOR);
    const anyStoryCriticalBelowFloor = applyStorySkeletonGate
      && adjustedDimensions.some((d) => this.isStoryCriticalDimension(d.name) && d.score < STORY_CRITICAL_FLOOR);
    const passed = totalScore >= PASS_THRESHOLD && !anyBelowFloor && !anyStoryCriticalBelowFloor;

    const overallMatch = content.match(
      /=== OVERALL ===[\s\S]*?(?:总评|Summary)[：:]\s*([\s\S]*?)$/,
    );
    const parsedOverallFeedback = overallMatch ? overallMatch[1]!.trim() : "(parse failed)";
    const skeletonFeedback = applyStorySkeletonGate
      ? this.buildStorySkeletonFeedback(foundation, language)
      : "";
    const overallFeedback = skeletonFeedback
      ? `${parsedOverallFeedback}\n\n${skeletonFeedback}`
      : parsedOverallFeedback;

    return { passed, totalScore, dimensions: adjustedDimensions, overallFeedback };
  }

  private applyStorySkeletonPenalties(
    dimensions: ReadonlyArray<{ readonly name: string; readonly score: number; readonly feedback: string }>,
    foundation: ArchitectOutput,
    language: "zh" | "en",
  ): Array<{ readonly name: string; readonly score: number; readonly feedback: string }> {
    return dimensions.map((dimension) => {
      const storyField = STORY_SKELETON_FIELDS.find((field) => dimension.name.includes(field.dimensionKeyword));
      if (!storyField) return dimension;

      const content = foundation[storyField.key];
      const missing = !content?.trim();
      const fallback = hasFallbackContent(content);
      if (!missing && !fallback) return dimension;

      const penalty = missing ? 45 : 55;
      const reason = language === "en"
        ? `${storyField.enName} is ${missing ? "missing" : "fallback-generated"}, so this dimension cannot pass as high quality.`
        : `${storyField.zhName}${missing ? "缺失" : "是 fallback 生成"}，该维度不能按高质量通过。`;

      return {
        ...dimension,
        score: Math.min(dimension.score, penalty),
        feedback: `${dimension.feedback}\n${reason}`,
      };
    });
  }

  private capTotalForMissingStorySkeleton(totalScore: number, foundation: ArchitectOutput): number {
    const weakCount = countFallbackSections(foundation) + countMissingStorySections(foundation);
    if (weakCount >= STORY_SKELETON_FIELDS.length) {
      return Math.min(totalScore, 69);
    }
    if (weakCount >= 3) {
      return Math.min(totalScore, 79);
    }
    return totalScore;
  }

  private isStoryCriticalDimension(name: string): boolean {
    return name.includes("world_engine_effectiveness")
      || name.includes("antagonist_effectiveness")
      || name.includes("first_10_chapter_pull");
  }

  private buildStorySkeletonFeedback(
    foundation: ArchitectOutput,
    language: "zh" | "en",
  ): string {
    const weakSections = STORY_SKELETON_FIELDS
      .map((field) => {
        const content = foundation[field.key];
        const missing = !content?.trim();
        const fallback = hasFallbackContent(content);
        if (!missing && !fallback) return null;
        return {
          field,
          reason: missing ? "missing" : "fallback",
        };
      })
      .filter((item): item is { field: typeof STORY_SKELETON_FIELDS[number]; reason: "missing" | "fallback" } => Boolean(item));

    if (weakSections.length === 0) return "";

    if (language === "en") {
      return [
        "## Story Skeleton Regeneration Requirements",
        ...weakSections.map(({ field, reason }) => (
          `- ${field.enName}: ${reason === "missing" ? "missing" : "fallback-generated"}; regenerate with concrete, book-specific content.`
        )),
        "- Next Architect pass must specify scarce resources, antagonist plan chain, first-10 ending hooks, distinct motivations, and reader promise where applicable.",
      ].join("\n");
    }

    return [
      "## 故事骨架重做要求",
      ...weakSections.map(({ field, reason }) => (
        `- ${field.zhName}：${reason === "missing" ? "缺失" : "fallback 生成"}；下一轮必须补成具体、贴合本书的内容。`
      )),
      "- 下一轮 Architect 必须具体补强：稀缺资源、反派计划链、前10章每章结尾钩子、人物动机差异、读者承诺等对应缺口。",
    ].join("\n");
  }
}
